{
 "title": "Pi-hole Exporter",
 "description": "Pi-hole dashboard using the custom pihole-exporter Prometheus exporter",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Pi-hole",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_status" }
   ]
  },
  {
   "title": "Domains being blocked",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pihole_gravity_domains_being_blocked"
    }
   ]
  },
  {
   "title": "Unique domains",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "pihole_unique_domains" }
   ]
  },
  {
   "title": "Top queries by domain",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_top_queries", "legendFormat": "{{ domain }}" }
   ]
  },
  {
   "title": "Replies by type",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_reply_type", "legendFormat": "{{ reply_type }}" }
   ]
  },
  {
   "title": "Top ads by domain",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_top_ads", "legendFormat": "{{ domain }}" }
   ]
  },
  {
   "title": "DNS queries all of types",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "pihole_dns_queries_today", "legendFormat": "{{ job }}" }
   ]
  },
  {
   "title": "% ads blocked",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "pihole_ads_percentage_today" }
   ]
  },
  {
   "title": "Ads blocked (today)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "pihole_ads_blocked_today", "legendFormat": "{{ job }}" }
   ]
  },
  {
   "title": "Queries cached/forwarded",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "pihole_queries_cached", "legendFormat": "Queries cached" },
    { "expr": "pihole_queries_forwarded", "legendFormat": "Queries forwarded" }
   ]
  },
  {
   "title": "DNS Query types",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "pihole_query_type", "legendFormat": "{{ query_type }}" }
   ]
  },
  {
   "title": "% of ads blocked",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "pihole_ads_percentage_today", "legendFormat": "{{ job }}" }
   ]
  },
  {
   "title": "Top queries",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
   "targets": [
    { "expr": "topk(15, pihole_top_queries)", "legendFormat": "{{ domain }}" }
   ]
  },
  {
   "title": "Top ads domains",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "topk(15, pihole_top_ads)", "legendFormat": "{{ domain }}" }
   ]
  },
  {
   "title": "Forward destinations",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "pihole_upstream_queries", "legendFormat": "{{ upstream }}" }
   ]
  },
  {
   "title": "Unique clients",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "pihole_clients_ever_seen", "legendFormat": "clients ever seen" }
   ]
  }
 ]
}